server:
  port: 8769
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/binjiez/product.git # 配置git仓库的地址
          search-paths: config-repo2                              # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: binjiez                               # git仓库的账号
          password: zjb35206035
